'use strict'

// Entity generated by the flow(s). See https://github.com/imrefazekas/harcon#quick-setup for details
// To learn about how workflows work: https://github.com/imrefazekas/harcon#workflows
module.exports = {
	name: 'Trade',

	// initialisation function, see https://github.com/imrefazekas/harcon#entity-configuration for details
	init: function (config, callback) {
		console.log( this.name + ' initiated with: ', config)
		callback()
	}


}
